[guild]
  ## if absent, the bot will try to run on the first guild it's connected to
#  id = <guild id>
  ## if present, users with this role will be considered when displaying statistics even if they have no sessions
#  enrolledRoleId = <role id>
  ## if present, users will be given this role while they have an active session
#  activeRoleId = <role id>
